Update RediStack package URL
d-exclaimation/pioneer-redis-pubsub pull request #6
Opened 2023-07-13 04:15 UTC by freysie

2023-07-13 04:18 UTC, freysie commented
Solves this warning which appears when using PioneerRedisPubSub together with Vapor’s Redis client:

> :warning: 'redis' dependency on 'https://github.com/swift-server/RediStack.git' conflicts with dependency on 'https://gitlab.com/mordil/RediStack.git' which has the same identity 'redistack'. this will be escalated to an error in future versions of SwiftPM.

2023-07-13 12:10 UTC, d-exclaimation commented
Thanks for catching the issue.

The version change is breaking the code and test, some changes are required before I can merge this. I don't remember why this package were updated to use the gamma version of RediStack, but I think it's probably better to switch back to the current (released) version of 1.4.1.

So here are my suggested changes:

on `Extensions/RedisClient+Broadcast.swift`, the broadcast function must be reverted back into having separate callback for message and unsubscribe 
```swift
public func broadcast(given broadcast: Broadcast<Data> = .init(), for channel: RedisChannelName) async -> Broadcast<Data> {
    do {
        try await subscribe(
            to: channel,
                messageReceiver: { _, msg in
                guard case .bulkString(.some(let buffer)) = msg else { return }
                let data = Data(buffer: buffer)
                Task {
                    await broadcast.publish(data)
                } 
            }, 
            onUnsubscribe: { _, _ in 
                Task {
                    await broadcast.close()
                }
            }
        ).get()
    } catch {
        await broadcast.close()
    }
    return broadcast
}
```

on `Tests/PioneerRedisPubSubTests/PioneerRedisPubSubTests.swift`, we need to also revert the configuration as well

```swift
override func setUp() async throws {
    let hostname = ProcessInfo.processInfo.environment["REDIS_HOSTNAME"] ?? "127.0.0.1"
    let port = Int(ProcessInfo.processInfo.environment["REDIS_PORT"] ?? "6379") ?? RedisConnection.Configuration.defaultPort

    client = try RedisConnectionPool(
        configuration: .init(
            initialServerConnectionAddresses: [
                .makeAddressResolvingHost(hostname, port: port)
            ], 
            maximumConnectionCount: .maximumActiveConnections(10), 
            connectionFactoryConfiguration: .init()
        ),
        boundEventLoop: eventLoopGroup.next()
    )
}
```

Feel free to alter these changes and improve upon it, as long as they pass the test

2023-07-13 12:10 UTC, d-exclaimation requested changes
Thanks for catching the issue.

The version change is breaking the code and test, some changes are required before I can merge this. I don't remember why this package were updated to use the gamma version of RediStack, but I think it's probably better to switch back to the current (released) version of 1.4.1.

So here are my suggested changes:

on `Extensions/RedisClient+Broadcast.swift`, the broadcast function must be reverted back into having separate callback for message and unsubscribe 
```swift
public func broadcast(given broadcast: Broadcast<Data> = .init(), for channel: RedisChannelName) async -> Broadcast<Data> {
    do {
        try await subscribe(
            to: channel,
                messageReceiver: { _, msg in
                guard case .bulkString(.some(let buffer)) = msg else { return }
                let data = Data(buffer: buffer)
                Task {
                    await broadcast.publish(data)
                } 
            }, 
            onUnsubscribe: { _, _ in 
                Task {
                    await broadcast.close()
                }
            }
        ).get()
    } catch {
        await broadcast.close()
    }
    return broadcast
}
```

on `Tests/PioneerRedisPubSubTests/PioneerRedisPubSubTests.swift`, we need to also revert the configuration as well

```swift
override func setUp() async throws {
    let hostname = ProcessInfo.processInfo.environment["REDIS_HOSTNAME"] ?? "127.0.0.1"
    let port = Int(ProcessInfo.processInfo.environment["REDIS_PORT"] ?? "6379") ?? RedisConnection.Configuration.defaultPort

    client = try RedisConnectionPool(
        configuration: .init(
            initialServerConnectionAddresses: [
                .makeAddressResolvingHost(hostname, port: port)
            ], 
            maximumConnectionCount: .maximumActiveConnections(10), 
            connectionFactoryConfiguration: .init()
        ),
        boundEventLoop: eventLoopGroup.next()
    )
}
```

Feel free to alter these changes and improve upon it, as long as they pass the test

2023-10-22 03:47 UTC, closed without merging

2023-10-22 03:47 UTC, d-exclaimation commented
Closed with #9